server:
  port: 9090

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:  ${PG_ADMIN}
    url: jdbc:postgresql://localhost:5432/hrmanagement
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root

jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}

rabbitmq:
  exchange-auth: auth-exchange
  registerKey: register-key
  queueRegister: register-queue
  registerMailQueue: mail-queue
  registerMailBindingKey: register-mail-key
  queueForgotPassword: forgot-password-mail-queue
  forgotPasswordMailBindingKey: forgot-password-mail-key
  queueResetPassword: reset-password-mail-queue
  resetPasswordMailBindingKey:  reset-password-mail-key